# Generated by Django 2.1.5 on 2019-10-06 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
